/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'karlamaria' at '07/07/16 12:55' with Gradle 2.14
 *
 * @author karlamaria, @date 07/07/16 12:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
